language: node_js
node_js:
- '6'
- '7'
- '8'
- '9'
- '10'
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- npm run lint
- npm run build
- npm run test:coverage
- npm run docs

after_script:
  - echo $TRAVIS_TEST_RESULT
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT

deploy:
  - provider: npm
    email: ackeedevelopment@gmail.com
    skip_cleanup: true
    api_key:
      secure: YQJ9k6gKzLd2SxTUDXacZSFNfkLPYiQOkPeDqB6jVEHA6QwRwhzNH/MyRabPxH1zlncMwULPzc2R/DPwFCF7Hx29OKDNDIMdX/Nc1NyjTg9Z9CFhUjuuqCmN8HWoY3mK39ZhnNZoA+fwqOZfgK53X2u1swcw60S/doHa5HvFszICCA9z4/xv78P4X7eEboeEtJq4l9OWFIQKTmlhU4ewIgK8ImSJEauNvqPnoTnADWavs7e5kG+wkUvnoHRRLZzBLERlK/TgnyrE1zMzN+DV5DJgdgsAMf8Cd1Peiv/reEGi13ZEVD1X9dUZG9g4usvAoTRKbhUEWnS4jNs6zpm7ye2jF8LOzkgRVsUL5vxIRSXz9M6BppicWovg2z3GztUHmOs5q0r70/0FbB4hSTFi7ld6MnBAcRAwX3tUhKX+U2hX41iPCPPBf3PiXGGkU/RCQ5FybN4vUM7FTNW+dRDy0qmlM7A+u0YUyCza1SzGc4cmV1uFK37KhYVxyD2HGRF1M473w0aBh0uTNEQJwnfG31dJcjmSsLOB/lTLh1xxGS1+M0iCIXFu5TgPzYhbQEWC6OQiq9awIXpRc4qdBk6DnE0nDgy1zoBEJ7dcLv/V2aO0wwwqDOxPowBTxPd+J/06jUtoMjJR8MGMiL5cpoPHTzM1KvHu81fz5Dvwz2543Ks=
    on:
      tags: true
      repo: AckeeCZ/axesor
  - provider: pages
    skip-cleanup: true
    github-token:
      secure: FKgEO9oT1WrMc5gLcNtsFMwQ/HjG2o+jj6ZLP/VQJzctW3crL6NMZuVf2lG9xjguuiGbyvzK0KF0//K43vy2Y/w03LWSq7uSJMx7a3/Q3gZV+B/joni6zROCiSCB/krP+T8OxqRmqeGq6kyYbSl5UFL9BRkR90PbPi6YP4y0f+nYVVg3iwkrkyRfJCzeWm/te0WbkduAqY4el5dKFTj4ra+Dq8A4lPKFoLVs5Rbjmx9/5TgLMBImhZTUJlPsVbSTbxw1PFLbW3kVnmwIygMfVcwjD2a0IOfU+b4sbEtjvdPj6d1vORrvJXN3qtU9KU3iF4GLoAxc0XbjpiXtwgI0STvq1D08IN71F/p+DgUHVEQpx6hk8qTGMdOVKj6+5b0gG+Ya18uSxCdLYEUq7zcQ89I6jrIE8EoUCkYQp+2wjswdqw41S3DyhrCYpmqMb6Co2XXFxyJnIF3j+HraZs3p6eKuSCgFjGmB6bCssJCjagPBD9yBEQWgu74uyOCxkpULo8gmo7+lnmFx6FQLDW+H3ndN4qaytWDHCuXsOwbBZu1Rgca+UtC37hj057QBt1H7/xB0XT5am+kItlJ+QjVDPf9C0hdhFn2cGZCgiB8WDS8/G0wPOhvQUeFFcBuFxJ7ly7TLfX0z2zF83KmgAoBq7XxNxO1OnKJKAhWrSjtlrYs=
    keep-history: true
    local-dir: "./docs"
    verbose: true
    on:
      branch: master
